default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: root
  password: password

development:
  <<: *default
  database: better-cherkasy-development

test:
  <<: *default
  database: better-cherkasy-test

production:
  <<: *default
  database: better-cherkasy-production
  password: thunder
