# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a95914b162bbe91d567f2ee12535eb4461d2348b55b377a0bb0f62f0ceb1dc9ae600b1c315076f792440ea0dbf70522e6c3f9c3f173741e08ccc3c53dad7f5d

test:
  secret_key_base: a87e740d49e94dfd9e3127e0ff1b2fe7760e27fc41797939b20f7da7775b5f7daeb0cfb3c77b9f339492d6e4671ecf9e11414284d7871ea648645e71a91c08aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 8a95914b162bbe91d567f2ee12535eb4461d2348b55b377a0bb0f62f0ceb1dc9ae600b1c315076f792440ea0dbf70522e6c3f9c3f173741e08ccc3c53dad7f5d
